### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by fafayqa** [lucafoscili/comfyui-lf#144]
It got error during install from ComfyUI v0.3.10 Manager, so it is useless for now - can you update/check it?

**Comment by lucafoscili** [comment]
I'm gonna need more info to check.
I'm using the nodes right now after updating all through the ComfyUI manager about an hour ago, everything looks fine.
![image](https://github.com/user-attachments/assets/4c90d551-2149-4172-a442-73bd50df27a4)

**Comment by fafayqa** [comment]
From the ComfyUI log during fetching the data:

FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json [DONE]
FETCH DATA from: Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
Install custom node 'LF Nodes'
Install: ['https://github.com/lucafoscili/comfyui-lf']
Download: git clone 'https://github.com/lucafoscili/comfyui-lf'
[!]
100%|██████████| 1228.0/1228.0 [00:01<00:00, 1214.96it/s]
100%|██████████| 1228.0/1228.0 [00:01<00:00, 1214.96it/s]
100%|██████████| 668.0/668.0 [00:01<00:00, 556.20it/s]
100%|██████████| 668.0/668.0 [00:01<00:00, 556.20it/s]
  3%|▌         | 367.0/11675.0 [03:31<1:48:42,  1.73it/s] Cmd('Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\git\bin\git.exe') failed due to: exit code(128)
  3%|▌         | 367.0/11675.0 [03:31<1:48:43,  1.73it/s]   cmdline: Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\git\bin\git.exe clone -v --recursive --progress -- https://github.com/lucafoscili/comfyui-lf Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-lf

**Comment by lucafoscili** [comment]
Hmm it might have to do with the fact that the images in the repo are massive, especially some of the workflows, so if the bandwidth is limited it could take a while.
It's strange though, I have a pretty crappy internet provider so I should have experienced this first-hand

**Comment by fafayqa** [comment]
What I will try is to simply extracting the zip to the cusom_nodes folder, remove the version and see what happens, as I think that is all the installer do (extracting/putting files in a folder inside custom_nodes) and ComfyUI will do the rest upon its start - am I correct?

**Comment by fafayqa** [comment]
What I will try is to simply extracting the zip to the cusom_nodes folder, remove the version from the name (so the extracted folder would become "comfyui-lf") and see what happens, as I think that is all the installer do (extracting/putting files in a folder inside custom_nodes) and ComfyUI will do the rest upon its start - am I correct?

**UPDATE**
Hahahahaaaa, yes - THAT WORKED LIKE A CHARM! :-)))
